### PR TITLE
Question form

### LINKED ISSUE #36: Add Question submission form

### PR DESCRIPTION
**Pull request by dfriedenbach**
Still need to transfer video pause/play functionality to this form and remove the redundant input.
resolves #36

### CODE REVIEW

**Comment by adpirz** [comment]
Daniel -- quick question, do you invoke checkUser anywhere? It's built in the factory, not sure if it was meant to be part of the send function

**Comment by dfriedenbach** [comment]
No, that's what I was talking about.  The idea was to add another input
field for the user to put their name in, but I hadn't gotten around to it
yet.  I think it would only be temporarily useful until we actually get
around to making user accounts and login, so I'm not sure if it's worth
doing at the moment

On Tue, Aug 11, 2015 at 10:51 AM, Adnan Pirzada notifications@github.com
wrote:

> Daniel -- quick question, do you invoke checkUser anywhere? It's built in
> the factory, not sure if it was meant to be part of the send function
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/axiomatic-blacksmith/axiomatic-blacksmith/pull/52#issuecomment-129990435
> .

## 

-Daniel Friedenbach

**Comment by adpirz** [comment]
Gotcha, thanks!
EDIT: and good work, this looks awesome!

**Comment by dfriedenbach** [comment]
Also if we wanted to just quickly mock up the ability to have usernames associated with questions, we could add the user input field and just not validate it at all.

**Pull request merged**
